# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-08 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, default='', null=True, verbose_name='商品详情页')),
                ('image_type', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='图片类型')),
                ('correlation_id', models.CharField(max_length=8, verbose_name='关联id')),
            ],
            options={
                'verbose_name': '详情页图片',
                'verbose_name_plural': '详情页图片',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='产品名称')),
                ('introduce', models.TextField(default='', verbose_name='产品简介')),
                ('price', models.SmallIntegerField(verbose_name='产品价格')),
                ('repertory', models.SmallIntegerField(verbose_name='库存')),
                ('of_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.SmallIntegerField(blank=True, choices=[(1, '商家'), (2, '用户')], null=True, verbose_name='用户类型')),
                ('account', models.SmallIntegerField(blank=True, null=True, verbose_name='账户余额')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商城用户',
                'verbose_name_plural': '商城用户',
            },
        ),
    ]
