# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-08 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='repertory',
            field=models.SmallIntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account',
            field=models.SmallIntegerField(default=0, verbose_name='账户余额'),
        ),
    ]
