# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-08 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_shop', '0002_auto_20190108_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='of_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
